export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const CERRAR_ALERTA = 'CERRAR_ALERTA';

export const CARGANDO = 'CARGANDO';

// INVENTARIO_ARBOLES
export const LISTAR_INVENTARIO = 'LISTAR_INVENTARIO';
export const AGREGAR_INVENTARIO = 'AGREGAR_INVENTARIO';
export const MENSAJE_INVENTARIO = 'MENSAJE_INVENTARIO';
export const INVENTARIO_ARBOL = 'INVENTARIO_ARBOL';
export const ELIMINAR_INVENTARIO = 'ELIMINAR_INVENTARIO';

//  INVENTARIO_CARACTERISTICA
export const OBTENER_CARACTERISTICAS = 'OBTENER_CARACTERISTICAS';
export const CREAR_CARACTERISTICA = 'CREAR_CARACTERISTICA';
export const MODIFICAR_CARACTERISTICA = 'MODIFICAR_CARACTERISTICA';
export const ELIMINAR_CARACTERISTICA = 'ELIMINAR_CARACTERISTICA';
export const MENSAJE_CARACTERISTICA = 'MENSAJE_CARACTERISTICA';

// ARBOLES_DATOS
export const OBTENER_ESPECIES = 'OBTENER_ESPECIES';
export const OBTENER_ARBOLES = 'OBTENER_ARBOLES';
export const MENSAJE_ESTADO = 'MENSAJE_ESTADO'